### ISSUE TITLE
Why app/Application is empty?

### ISSUE THREAD

**Issue by absoftware** [hibit-dev/laravel9-ddd#1]
Hello! Thank you for this repository. It helps me to understand Laravel and DDD. I really like your solution. However I wonder, because your articles explain that Application deals with domain and infrastructure, not UI. So maybe instead of

```
class UserController extends Controller
{
    public function index(Request $request, UserRepository $userRepository): JsonResponse
    {
        $offset = $request->query('offset');
        $email = $request->query('email');
        $name = $request->query('name');

        $criteria = UserSearchCriteria::create(
            !empty($offset) && !is_array($offset) ? (int) $offset : null,
            !empty($email) && !is_array($email) ? $email : null,
            !empty($name) && !is_array($name) ? $name : null,
        );

        $criteria->sortBy(new CriteriaSort(CriteriaField::fromString('name'), CriteriaSortDirection::ASC));

        $users = $userRepository->searchByCriteria($criteria);

        return response()->json([
            'users' => array_map(fn (User $user) => $user->asArray(), $users)
        ]);
    }
}
```

we could write

```
use App/Application/DataTransferObjects/User;
use App/Application/DataTransferObjects/UserSearchCriteria;
use App/Application/UseCases/Users;

class UserController extends Controller
{
    public function index(Request $request, Users $users): JsonResponse
    {
        $offset = $request->query('offset');
        $email = $request->query('email');
        $name = $request->query('name');

        $userSearchCriteria = UserSearchCriteria::create($offset, $email, $name);
        $users = $users->search($userSearchCriteria);

        return response()->json([
            'users' => array_map(fn (User $user) => $user->asArray(), $users)
        ]);
    }
}
```

and

```
namespace App/Application/UseCases;

use App/Domain/User/UserRepository;

class Users 
{
    public function __construct(UserRepository $userRepository) { ... }
}
```

where `Users` has injected `UserRepository`. I ask because isn't it a "crime" to use domain's objects in UI layer? Then we could control validity of the architecture controlling `use` commands not allowing any `use App/Domain/...` in UI layer for example and all operations must go through the Application.

**Comment by tmekinyan** [comment]
Hello!

In Domain-Driven Design, you have the flexibility to use the current and deeper levels. Your suggestion resembles the CQRS pattern, which involves separating queries for data retrieval and commands for updating data stores. Keep in mind that it's important to validate your business logic at the Domain level. Typically, this can be achieved by employing Value Objects (VOs) instead of relying on primitive data types.

It's always a matter of balancing priorities: you can invest time in achieving a perfect structure or start with a solid base and continuously improve it over time.

**Comment by absoftware** [comment]
Thank you for the explanation. If there is another concept about this named CQRS then all seems to be right.
